name: Daily News Sentiment

on:
  schedule:
    - cron: "0 8 * * *"   # Run at 08:00 UTC
    - cron: "0 20 * * *"  # Run at 20:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests nltk
          python -c "import nltk; nltk.download('vader_lexicon')"

      - name: Run script
        run: python main.py  # make sure this writes index.html to the repo root

      - name: Commit updated index.html
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update dashboard" || echo "No changes"
          git push origin main
