name: Daily News Sentiment

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests nltk
          python -c "import nltk; nltk.download('vader_lexicon')"

      - name: Run script
        run: python main.py  # or whatever your script is called

      - name: Copy output to gh-pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin gh-pages
          git switch gh-pages
          git restore --source=main index.html  # if your script now writes to index.html
          git add index.html
          git commit -m "Update dashboard" || echo "No changes"
          git push origin gh-pages
